### ISSUE TITLE
シフトがBook中で一つしか生成されない

### ISSUE THREAD

**Issue by kurage10** [pumpkinheader/reverseShift#7]
１つのPositionについてしか完全なシートが生成されず、その他は空のシートが生成されてしまいます。
シートの枚数はPositionの数と同じ数になっています。

**Comment by pumpkinheader** [comment]
失礼…！ちゃんとテストできてないやつリリースしてしまったか…シフトの名前はついてます？？

**Comment by kurage10** [comment]
おそらく最初に処理されたひとつだけ名前・中身の逆シフトも完全なものが出てて、その他はsheet 2 ,sheet 3っていうタイトルで中身が白紙になっています！

**Comment by pumpkinheader** [comment]
ぐぬぬ手元で再現できない。ソース元のシフトをメールか何かで送ってくださらないか

**Comment by kurage10** [comment]
遅れてすみません、先ほどpumpkinde@gmail.comにメールを送りました！
